#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : bookdemo  # The title of the book. Will be placed in the left navbar.
author                      : Qiusheng Wu  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

parse:
  myst_extended_syntax: true

# Online stuff
repository:
  url                       : https://github.com/giswqs/bookdemo
  path_to_book              : bookdemo

launch_buttons:
  notebook_interface        : jupyterlab
  binderhub_url             : https://mybinder.org

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

sphinx:
  config:
    html_extra_path: ["_build/html"]